### PR TITLE
Update Dockerfile for Visual Studio 2015 CTP 5 projects

### PR DESCRIPTION
**Pull request by KentaroAOKI**
Hi,

I update Dockerfile for Visual Studio 2015 CTP 5 and I was able to run following asp.net 5 project on updated docker image.

https://github.com/KentaroAOKI/Aspnet5WebApplicationForDocker

Thanks.

Kentaro

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
This is almost the same thing as #28 as it installs `git`, `grunt`, `node`. Let's move the discussion over there.

**Comment by KentaroAOKI** [comment]
Hi,

Could you see following the blog.
http://blogs.msdn.com/b/webdev/archive/2014/11/12/announcing-asp-net-features-in-visual-studio-2015-preview-and-vs2013-update-4.aspx

Visual Studio 2015 "ASP.NET 5 Starter Web" template contains bower.json to use with Bower to get frontend packages, package.json to use with NPM to get Grunt, and gruntfile.js to manage tasks defined by project.json scripts.

We use the Visual Studio to create some ASP.NET Applications almost everyone and We need a solution for Visual Studio Users.

I have two idea. First is aspnet image + forVS2015 image. Second is aspnet one image.

First is
https://github.com/KentaroAOKI/aspnet-docker/blob/master/vs2015/Dockerfile
Second is
https://github.com/KentaroAOKI/aspnet-docker/blob/master/1.0.0-beta2/Dockerfile

Thanks.

**Comment by KentaroAOKI** [comment]
Hi,

Visual Studio 2015 "ASP.NET 5 Starter Web" template contains bower.json to use with Bower to get frontend packages, package.json to use with NPM to get Grunt, and gruntfile.js to manage tasks defined by project.json scripts.

http://blogs.msdn.com/b/webdev/archive/2014/11/12/announcing-asp-net-features-in-visual-studio-2015-preview-and-vs2013-update-4.aspx

We use Visual Studio 2015 to create some ASP.NET Applications and We need a solution for Visual Studio Users.
I have two idea. First is aspnet image with forVS2015 image. Second is one aspnet image.

First is
https://github.com/KentaroAOKI/aspnet-docker/blob/master/vs2015/Dockerfile

Second is 
https://github.com/KentaroAOKI/aspnet-docker/blob/master/1.0.0-beta2/Dockerfile

Thanks,

**Comment by KentaroAOKI** [comment]
@ahmetalpbalkan Thanks.

**Comment by msotclas** [comment]
Hi __@KentaroAOKI__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by ahmetalpbalkan** [comment]
Duplicate of #28.

**Pull request closed without merging**
