### PR TITLE
Add MONO_THREADS_PER_CPU=2000 to prevent dnu restore failing

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
This was pretty annoying in #63 #80. Also causing CI to fail intermittently.

### CODE REVIEW

**Comment by friism** [comment]
nice

**Comment by akoeplinger** [comment]
FYI it won't be required in beta8 as I put the workaround in dnu itself: https://github.com/aspnet/dnx/pull/2620

**Comment by ahmetalpbalkan** [comment]
@akoeplinger awesome. Now this makes me think if 2000 was overkill or could potentially burn people's machines.

**Comment by akoeplinger** [comment]
@ahmetalpbalkan I wouldn't worry, many people used 2000 and to my knowledge nobody complained. I chose 50 because it's capped there in the new threadpool that is arriving in Mono 4.2, so setting it higher doesn't make sense.

**Pull request merged**
