### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by glennc**
Mis-predicted url in readme.

### CODE REVIEW

**Comment by glennc** [comment]
I did this quick :). I will clone it and make it and check it out properly.

**Comment by glennc** [comment]
Ok, that looks like it fixes everything.

**Comment by muratg** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
Looks wrong to me. README.md is not a symlink in 95f6482.

**Comment by glennc** [comment]
My bad, it was a hard link...

**Comment by glennc** [comment]
@ahmetalpbalkan you good with me merging this one now?

**Comment by ahmetalpbalkan** [comment]
:+1:

**Pull request merged**
