### PR TITLE
Add Nano Server ltsc2016 tags

### PR DESCRIPTION
**Pull request by MichaelSimons**
`ltsc2016` is the new tag that is being added everywhere to identify Windows Server 2016.  All previously produced tags are maintained to prevent breaking users who have taken a dependency on them.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@natemcmaster - Can you take another look?  I renamed the `nanoserver` folder to `nanoserver-ltsc2016` in order to fixup CI.

**Comment by natemcmaster** [comment]
Looks good. :shipit:

**Comment by MichaelSimons** [comment]
Last minute catch from Windows led to a rename of ltsc2016 to sac2016.  Nano Server RS1 is from semi-annual channel not the long-term support channel (https://docs.microsoft.com/en-us/windows-server/get-started/semi-annual-channel-overview)

**Comment by natemcmaster** [comment]
👌

**Pull request merged**
