### PR TITLE
Add an rc1-update1 image.

### PR DESCRIPTION
**Pull request by glennc**
A new image for the RC1 bugfix release. It contained a new runtime but no new packages.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
wow our CI average per PR is 30 minutes.

**Comment by glennc** [comment]
@ahmetalpbalkan Yeah, presumably the time is downloading all the packages for so many apps. 2 apps per image with many packages each.

I take it you are good with the PR though?

**Comment by ahmetalpbalkan** [comment]
LGTM.

**Comment by ahmetalpbalkan** [comment]
Weird enough, merging this broke master after 45 minutes of CI.

**Pull request merged**
