### PR TITLE
Add beta6 Dockerfile

### PR DESCRIPTION
**Pull request by yanchenw**

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
Hey @yanchenw looks like beta6 is not tagged on Home repo https://github.com/aspnet/Home/tags and thus cannot locate the samples/ directory. Hence the CI is failing. @glennc @danroth27 when will the beta6 tag will be pushed to the Home repo?

**Comment by Eilon** [comment]
@pranavkm is in charge of tagging releases.

**Comment by kichalla** [comment]
Also we need to update the samples and create a directory for beta6 : https://github.com/aspnet/Home/tree/dev/samples

**Comment by ahmetalpbalkan** [comment]
@kichalla @pranakvm from a CI tests standpoint, we first checkout to the tag (i.e. `beta6`) on the aspnet/Home repo and then look for the path `1.0.0-beta6`. For instance, for beta5, we pick the sample apps from:

    https://github.com/aspnet/Home/tree/v1.0.0-beta5/samples/1.0.0-beta5

Therefore, while tagging `beta6` over there, please make sure `samples/1.0.0-beta6` directory is included in the tag. Last time we had to change the tag after the release to fix this.

**Comment by kichalla** [comment]
@ahmetalpbalkan @yanchenw The samples and tag have been created, but not sure how do you kick off the CI run again to verify if all is ok

**Comment by ahmetalpbalkan** [comment]
I just kicked off another run.

**Comment by kichalla** [comment]
I suspect this would run fail as beta6 sample has a Dockerfile already in it (https://github.com/aspnet/Home/blob/dev/samples/1.0.0-beta6/HelloMvc/Dockerfile)...

I think we need to even have docker files for beta4 and beta5 in the samples and then can remove the following code?: https://github.com/aspnet/aspnet-docker/blob/master/.ci/build-app-image.sh#L21-L25

**Comment by ahmetalpbalkan** [comment]
@kichalla it would overwrite the existing Dockerfile. :-) 

Even if you add dockerfiles to the old versions directories, as long as you don't re-tag versions beta4/5 to include this change, it won't work.

We can modify the script to not to overwrite if the file already exists, however we're setting extra stuff like DNU_TRACE in our drop-in Dockerfile, so I think we're good until this breaks.

**Comment by kichalla** [comment]
Ah ok, thanks and the build also passed :smile: 

:shipit:

**Comment by ahmetalpbalkan** [comment]
Docker Hub builds kicked off. We're live if they pass. https://registry.hub.docker.com/u/microsoft/aspnet/builds_history/82542/

**Pull request merged**
