### PR TITLE
Updated NODE_VERSION to LTS 6.9.4

### PR DESCRIPTION
**Pull request by ClaytonHunt**
Title says it all, based on the conversation in the Issues I have created this pull request which brings the docker images up to the current LTS version of node

### CODE REVIEW

**Comment by ClaytonHunt** [comment]
@natemcmaster Please review the changes, and thanks! I can't seem to add reviewers so I'm just leaving this comment. Let me know if I need to change anything or if there are problems

**Comment by ClaytonHunt** [comment]
Ok, first time I've rebased :) should be all clear now.

**Comment by natemcmaster** [comment]
It looks like the rebase restored the dockerfiles in `1.0.1/jessie/*`. Can you remove this folder from your PR?

**Comment by ClaytonHunt** [comment]
Sorry for all this back and forth, I think it should be good now.

**Comment by natemcmaster** [comment]
Thanks for the contribution! Should be available via Docker Hub soon.

**Comment by ClaytonHunt** [comment]
Awesome! Thanks for putting up with my mistakes :)

**Comment by natemcmaster** [comment]
No worries. The Docker Hub build passed. Re-pull and your images should have the update. 😄

**Pull request merged**
