### PR TITLE
updates for rc1

### PR DESCRIPTION
**Pull request by glennc**
Getting this one ready, I want to see if the CI works still and that our names are all working.

### CODE REVIEW

**Comment by glennc** [comment]
Seems to be strange, seemingly unrelated, issues with circleci. Anyone else know anything about them?

**Comment by akoeplinger** [comment]
I see the following in the logs for the coreclr based DNX:

```
Could not open /etc/lsb_release. OS version will default to the empty string.

Error: Unable to resolve project from /app
```

**Comment by glennc** [comment]
Yeah, that has been there for a couple of releases. Though setting ENV DNX_RUNTIME_ID should make it go away.

**Comment by glennc** [comment]
Lots of issues with the Home repo samples. I have been making commits over there and re-spining this.

**Pull request merged**
