### PR TITLE
Add beta3

### PR DESCRIPTION
**Pull request by friism**

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@friism__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by ahmetalpbalkan** [comment]
Thanks for PR! Build is failing at the moment, can you please take a look?

Also there shouldn't be two READMEs, please remove the one in beta2. We just need to keep one readme next to a Dockerfile so that Hub can generate a description from readme file. In this case we decided to keep it next to latest. it'll be fine if you just remove the old one in beta2.

Can you also squash the commits into one please?

**Comment by friism** [comment]
@ahmetalpbalkan for some reason, the two sample apps are locked to beta1. I've sent an update to update them to beta3: https://github.com/aspnet/Home/pull/348

**Comment by friism** [comment]
@msotclas I've gotten the CLA signed, thanks!

**Comment by friism** [comment]
@ahmetalpbalkan commits squashed, beta2 README removed.

**Comment by ahmetalpbalkan** [comment]
LGTM. I'll merge once samples are fixed. I guess there's no need to hurry at this point.

**Comment by JontyMC** [comment]
I had to change the last line of the docker file to:
```
ENV PATH $PATH:$KVM_USER_HOME/runtimes/default/bin
```

**Comment by ahmetalpbalkan** [comment]
@friism sounds about right. I remember you using /runtimes/.. at some point?

**Comment by friism** [comment]
Lemme take a look

**Comment by ahmetalpbalkan** [comment]
Oh sorry that was the nightly PR #36.

**Comment by akoeplinger** [comment]
@ahmetalpbalkan beta3 runtimes are now in ~/.k/runtimes/..

**Comment by ahmetalpbalkan** [comment]
@akoeplinger thanks. We need to find out if it respects the install path we provide.

**Comment by friism** [comment]
Fix pushed, thanks @JontyMC

**Comment by ahmetalpbalkan** [comment]
@friism the samples are updated however it's now failing with a different error. ([output](https://circle-artifacts.com/gh/aspnet/aspnet-docker/34/artifacts/0/home/ubuntu/aspnet-docker/container-logs/c597055c99c4.log)) can you please check?

```2015-03-12T20:57:22.017488921Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DefaultHost]: Project path: /app
2015-03-12T20:57:22.017651922Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DefaultHost]: Project root: /app
2015-03-12T20:57:22.017723844Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DefaultHost]: Packages path: /root/.kpm/packages
2015-03-12T20:57:22.035903240Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DependencyWalker]: Walking dependency graph for 'app Asp.Net,Version=v5.0'.
2015-03-12T20:57:22.138845141Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/Microsoft.Framework.Runtime.dll Information : 0 : [ProjectReferenceDependencyProvider]: app 1.0.0
2015-03-12T20:57:22.140820374Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/Microsoft.Framework.Runtime.dll Information : 0 : [NuGetDependencyResolver]: Kestrel 1.0.0-beta3, Microsoft.AspNet.Diagnostics 1.0.0-beta3, Microsoft.AspNet.Hosting 1.0.0-beta3, Microsoft.AspNet.Server.WebListener 1.0.0-beta3, Microsoft.AspNet.StaticFiles 1.0.0-beta3, Microsoft.AspNet.Server.Kestrel 1.0.0-beta3, Microsoft.AspNet.RequestContainer 1.0.0-beta3, Microsoft.AspNet.FileProviders 1.0.0-beta3, Microsoft.AspNet.Http.Core 1.0.0-beta3, Microsoft.Framework.Logging 1.0.0-beta3, Microsoft.Framework.OptionsModel 1.0.0-beta3, Newtonsoft.Json 6.0.6, Microsoft.AspNet.FeatureModel 1.0.0-beta3, Microsoft.AspNet.Http 1.0.0-beta3, Microsoft.Framework.ConfigurationModel 1.0.0-beta3, Microsoft.Net.Http.Server 1.0.0-beta3, Microsoft.Net.WebSocketAbstractions 1.0.0-beta3, Microsoft.AspNet.Http.Extensions 1.0.0-beta3, Microsoft.AspNet.FileProviders.Interfaces 1.0.0-beta3, Microsoft.AspNet.Http.Interfaces 1.0.0-beta3, Microsoft.AspNet.WebUtilities 1.0.0-beta3, Microsoft.Net.Http.Headers 1.0.0-beta3, Microsoft.Framework.Logging.Interfaces 1.0.0-beta3, Microsoft.Framework.DependencyInjection 1.0.0-beta3, Microsoft.Net.WebSockets 1.0.0-beta3, Microsoft.Framework.Runtime.Interfaces 1.0.0-beta3
2015-03-12T20:57:22.178069023Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/Microsoft.Framework.Runtime.dll Information : 0 : [ReferenceAssemblyDependencyResolver]: gac/mscorlib 4.0.0.0, gac/System 4.0.0.0, gac/System.Core 4.0.0.0, gac/Microsoft.CSharp 4.0.0.0
2015-03-12T20:57:22.180077959Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/Microsoft.Framework.Runtime.dll Information : 0 : [DependencyWalker]: Resolved dependencies for app in 143ms
2015-03-12T20:57:22.183107476Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/klr.host.dll Information : 0 : [LoaderContainer]: Load name=Microsoft.AspNet.Hosting
2015-03-12T20:57:22.198661862Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/klr.host.dll Information : 0 : [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Hosting in 15ms
2015-03-12T20:57:22.201234714Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/klr.host.dll Information : 0 : [LoaderContainer]: Load name=Microsoft.Framework.ConfigurationModel
2015-03-12T20:57:22.202052039Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/klr.host.dll Information : 0 : [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.ConfigurationModel in 0ms
2015-03-12T20:57:22.202659841Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/klr.host.dll Information : 0 : [LoaderContainer]: Load name=Microsoft.Framework.DependencyInjection
2015-03-12T20:57:22.203594637Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/klr.host.dll Information : 0 : [NuGetAssemblyLoader]: Loaded name=Microsoft.Framework.DependencyInjection in 0ms
2015-03-12T20:57:22.204005843Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/klr.host.dll Information : 0 : [LoaderContainer]: Load name=Microsoft.AspNet.Http
2015-03-12T20:57:22.204568101Z /opt/kre/packages/KRE-Mono.1.0.0-beta1/bin/klr.host.dll Information : 0 : [NuGetAssemblyLoader]: Loaded name=Microsoft.AspNet.Http in 0ms
2015-03-12T20:57:22.222870765Z System.InvalidOperationException: No service for type 'Microsoft.Framework.DependencyInjection.ServiceLookup.IServiceManifest' has been registered.
2015-03-12T20:57:22.222870765Z   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService (IServiceProvider provider, System.Type serviceType) [0x00000] in <filename unknown>:0 
2015-03-12T20:57:22.222951590Z   at Microsoft.Framework.DependencyInjection.ServiceProviderExtensions.GetRequiredService[IServiceManifest] (IServiceProvider provider) [0x00000] in <filename unknown>:0 
2015-03-12T20:57:22.222951590Z   at Microsoft.AspNet.Hosting.HostingServices.Import (IServiceProvider fallbackProvider) [0x00000] in <filename unknown>:0 
2015-03-12T20:57:22.222951590Z   at Microsoft.AspNet.Hosting.HostingServices.Create (IServiceProvider fallbackServices, IConfiguration configuration) [0x00000] in <filename unknown>:0 
2015-03-12T20:57:22.222951590Z   at Microsoft.AspNet.Hosting.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
2015-03-12T20:57:22.222951590Z   at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
2015-03-12T20:57:22.222951590Z   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
```

**Comment by ahmetalpbalkan** [comment]
@friism it looks like Home/samples are updated with beta3 stuff and now 1.0.0-beta1 imaage cannot run these? https://circle-artifacts.com/gh/aspnet/aspnet-docker/36/artifacts/0/home/ubuntu/aspnet-docker/container-logs/ee6864cee948.log can you please check if this is the case, if so we can probably discontinue the old versions.

**Comment by friism** [comment]
@ahmetalpbalkan taking a look now

**Comment by ahmetalpbalkan** [comment]
@friism looks like we fixed it in #41. can you please rebase so we can kick off another CI run?

**Comment by friism** [comment]
@ahmetalpbalkan done, crossing my fingers for build :-)

**Comment by ahmetalpbalkan** [comment]
@friism unfortunately fails with [this](https://circle-artifacts.com/gh/aspnet/aspnet-docker/39/artifacts/0/home/ubuntu/aspnet-docker/container-logs/28746bd054c7.log).

**Comment by friism** [comment]
looking

**Comment by friism** [comment]
Weird, works fine on my local machine with master checkout of the home samples. Checking the circle crap.

**Comment by friism** [comment]
@ahmetalpbalkan I don't get it, the CircleCI errors are not like what you post. Where are you getting that? I'm looking at https://circleci.com/gh/aspnet/aspnet-docker/39

**Comment by friism** [comment]
@ahmetalpbalkan the log that you're posting, which of the sample project is that?

**Comment by friism** [comment]
@ahmetalpbalkan is there any public chat/IRC place where you consistently hang out? Like vnext Jabbr? https://jabbr.net/#/rooms/AspNetvNext

**Comment by friism** [comment]
alright, trying to build the images the way that you do: https://github.com/aspnet/aspnet-docker/blob/master/.ci/build-app-image.sh#L14

**Comment by ahmetalpbalkan** [comment]
@friism I grabbed the container id from CircleCI output logs, clicked on Artifacts on CircleCI and you can see that all containers have log files over there. We save container logs in each build so that we can troubleshoot the problem like this.

you can find me on irc.freenode.net 7/24 (ahmetalpbalkan).

**Comment by vlesierse** [comment]
I've looked into this problem and it appears that the version tags doesn't match with the versions in the project.json of samples. They are still on beta1 in the beta3 tag.

My suggestion is to create a sample application within this repository. This repository will be less dependent on what is happening in the Home repository.

**Comment by friism** [comment]
Ya, it looks like they didn't move the beta3 tag: https://github.com/aspnet/Home/releases

**Comment by ahmetalpbalkan** [comment]
@friism @vlesierse is the project.json the only problem? If so, just like we inject Dockerfiles, we can "sed -i" the versions as well. I'm not really a big fan of maintaining samples. :-(

**Comment by vlesierse** [comment]
@ahmetalpbalkan for this particular case it is. But there is not guarantee for breaking code changes in the future.

**Comment by ahmetalpbalkan** [comment]
@vlesierse feel free to fork or create another samples repo if you like. we can refer to your repos in the CI tests.

**Comment by vlesierse** [comment]
I have forked the `aspnet/Home` repository and changed the tags to the right commits. Please feel free to change the ci to `vlesierse/Home`.

**Comment by ahmetalpbalkan** [comment]
@vlesierse feel free to send the PR. :smile: it's better when proposal comes from you.

**Comment by friism** [comment]
It feels weird to be relying on samples hosted in @vlesierse's account, but up to you guys.

@ahmetalpbalkan what about factoring the tests into a separate repo that has the (non-broken) samples?

**Comment by vlesierse** [comment]
I agree that this isn't sustainable solution for the future. I will at least create an issue to the `aspen/Home` repo that it takes care of the samples as well when the releases are tagged.

**Comment by davidfowl** [comment]
Do we just need to retag the home branch with beta3 working samples?

**Comment by ahmetalpbalkan** [comment]
@davidfowl looks like it.

**Comment by vlesierse** [comment]
Yes, that should be all.

**Comment by ahmetalpbalkan** [comment]
@feiling Tests are passing now. Merging and updating Docker Hub.

**Comment by friism** [comment]
:dancer:

**Comment by ahmetalpbalkan** [comment]
Added build:

**Comment by vlesierse** [comment]
Great

**Pull request merged**
