### PR TITLE
Add beta8

### PR DESCRIPTION
**Pull request by glennc**
Beta 8 Dockerfiles

### CODE REVIEW

**Comment by glennc** [comment]
@ahmetalpbalkan @anurse give me a shipit on this one?

**Comment by ahmetalpbalkan** [comment]
CI :green_apple: =:shipit:.

but I don't think we should have these trailing commas. no idea how they got in there in the first place.

image

**Comment by glennc** [comment]
Yeah, I was just copying what was there before. I will do another PR to get rid of them after this one.

**Comment by ahmetalpbalkan** [comment]
#:100: :confetti_ball:

**Comment by ahmetalpbalkan** [comment]
@glennc next time can you use your fork as PR branch? Every time you push commit to here (any branch) Docker Hub triggers a build.

**Comment by glennc** [comment]
Sure thing.

**Pull request merged**
