### PR TITLE
Add 2.0.0-preview1 images

### LINKED ISSUE #215: Create .NET Core 2.0 docker images
Once available, the `latest` tag should move to 2.0 and `lts` should move to `1.1`.

The 2.0 images will need to react to changes in how crossgen assets are loaded:

 - DOTNET_HOSTING_OPTIMIZATION_CACHE has been retired https://github.com/dotnet/core-setup/pull/1330
 - Package store layout on disk is different from current optimization cache. See https://github.com/dotnet/core-proposals/blob/master/DotNetCore-SharedPackageStore.md

### PR DESCRIPTION
**Pull request by natemcmaster**
Resolves #215 

TODO before merging:
 - [x] Verify assemblies are actually loaded from the package runtime store. At the moment, this fails because dotnet-new does not use the latest build of preview1 packages and because of https://github.com/aspnet/MetaPackages/issues/89
- [x] Restore from nuget.org, not myget.org
 - [x] FROM `microsoft/dotnet`, not `microsoft/dotnet-nightly`
  - [x] Update packages cache and download links to 2.0.0-preview1-final when it is ready

### CODE REVIEW

**Comment by natemcmaster** [comment]
Updated, ready for final review. 

:watch: https://github.com/dotnet/dotnet-docker/pull/238 for base images

**Comment by natemcmaster** [comment]
FYI the nanoserver build definition has been updated

**Comment by MichaelSimons** [comment]
@natemcmaster - regarding the nano build definition.  I believe the `tags.runtime` and `tags.sdk` variables need to be updated in order to get the images pushed.

**Comment by natemcmaster** [comment]
Good catch. I had made those changes and forgot to save before closing the tab. :-/ Should be updated now.

**Pull request merged**
