### PR TITLE
Add <major>-<minor> non-manifest tags

### LINKED ISSUE #318: Add tags to support customers that want/need to stay pinned to Nano Server RS1
Currently there is one fully qualified tag (per image variant - runtime/build) that is not backed by a manifest which allows users to be pinned to Nano Server RS1.

Runtime --> 2.0.0-nanoserver
Build --> 2.0.2-nanoserver

An additional tag should be added that allow users to pin to Nano Server RS1 but still get able to automatically pick up patch versions.

2.0-nanoserver

The same should be done for the Nano Server RS3 tags.

### PR DESCRIPTION
**Pull request by MichaelSimons**
Fixes #318 

cc @richlander

### CODE REVIEW

**Comment by natemcmaster** [comment]
Changes look fine, however it looks like the Linux build is failing.

```
$ /bin/bash -c "docker run --add-host dockerhost:$(ifconfig eth0 | grep -oP 'inet addr:\K\S+') -v /var/run/docker.sock:/var/run/docker.sock testrunner powershell -File ./test/test.ps1 -Folder $folder_filter -HostIP dockerhost"
container_linux.go:247: starting container process caused "exec: \"powershell\": executable file not found in $PATH"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"powershell\": executable file not found in $PATH".
```

It's probably unrelated to your change, but any ideas what might be different?

**Comment by MichaelSimons** [comment]
Last night's official build failed with the same issue.  I noticed the Dockerfile is pretty old and doesn't specify an explicit version of PS.  It is using an extremely old version of Docker.  Before spending too much time, it may be best to upgrade to https://github.com/dotnet/dotnet-docker/blob/master/test/Dockerfile.linux.testrunner

**Comment by MichaelSimons** [comment]
@Ravimeda was going to take a look at this.  Ravi, please respond here with your findings.

**Comment by natemcmaster** [comment]
Related to this, perhaps? https://www.traviscistatus.com/incidents/v4jnp6nkgzqx

**Comment by ravimeda** [comment]
In **dotnet-docker** https://github.com/aspnet/aspnet-docker/blob/master/test/Dockerfile.testrunner.linux#L2-L3
```
docker build -t testrunner -f ./test/Dockerfile.testrunner.linux .
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock testrunner powershell -File test/test.ps1
```
Succeeds (no errors).

Whereas, **aspnet** https://github.com/dotnet/dotnet-docker/blob/master/test/Dockerfile.linux.testrunner#L2-L3
```dockerfile
docker build -t testrunner -f ./test/Dockerfile.linux.testrunner .
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock testrunner powershell -File build-and-test.ps1 -UseImageCache
```

Fails -
```
docker : container_linux.go:265: starting container process caused "exec: \"powershell\": executable file not found in $PATH"
At line:1 char:1
+ docker run --rm -v /var/run/docker.sock:/var/run/docker.sock testrunn ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (container_linux...found in $PATH":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"powershell\": executable file not found in $PATH".
```

**Comment by ravimeda** [comment]
Running the following commands in aspnet -

1. docker build -t testrunner -f ./test/Dockerfile.testrunner.linux .
2. docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock testrunner
3. powershell

Results in `bash: powershell: command not found`

Not sure why PowerShell in unavailable, though the log from build command says -
`https://packages.microsoft.com/ubuntu/16.04/prod xenial/main amd64 powershell amd64 6.0.0-beta.9-1.ubuntu.16.04 [54.0 MB]`

This version is newer than the one used in dotnet-docker `v6.0.0-beta.6` (https://github.com/dotnet/dotnet-docker/blob/master/test/Dockerfile.linux.testrunner#L29)

**Comment by ravimeda** [comment]
PowerShell is now **pwsh** as per https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-beta.9
>Starting from this release, the PowerShell Core executable is renamed to be pwsh

**Comment by ravimeda** [comment]
Retry the checks after merging https://github.com/aspnet/aspnet-docker/pull/320

**Pull request merged**
