### PR TITLE
Set RestoreUseSkipNonexistentTargets=false in the 2.0 image to workaround changes between the 2.1.4 and 2.1.101 SDK

### PR DESCRIPTION
**Pull request by natemcmaster**
Workaround https://github.com/Microsoft/DockerTools/issues/87.

Addresses #388 

FYI @glennc @nkolev92 @Eilon

### CODE REVIEW

**Comment by alexvy86** [comment]
@natemcmaster do you know if there are any plans to implement the same workaround in the [`dotnet-docker` images](https://github.com/dotnet/dotnet-docker)?

**Comment by natemcmaster** [comment]
No immediate plans. Why do you ask?

We chose to put this here as a targeted workaround because the Visual Studio tooling generates a reference to `microsoft/aspnetcore-build`. We'd like to minimize number of places that have workarounds.

**Comment by alexvy86** [comment]
In the `Dockerfile` that VS tooling adds to console app projects, the build stage is based on `microsoft/dotnet:2.0-sdk`, thus my question. In my case the broken CI builds are for console apps. I went to the `dotnet-docker` images repo and didn't see any issues/PRs like yours there, so I was wondering if the fixes were particular to ASP .NET Core projects for any reason.

**Comment by natemcmaster** [comment]
Oofta, I don't think anyone pointed that out. I'll use my internal email powers to forward this along.

**Comment by natemcmaster** [comment]
@alexvy86 in the meantime, you can always add `ENV RestoreUseSkipNonexistentTargets false` to your own file to workaround, or change any calls to dotnet-restore to `dotnet restore -p:RestoreUseSkipNonexistentTargets=false`

**Comment by alexvy86** [comment]
Yes, I did find those two solutions and already applied one, thanks!

**Comment by AceHack** [comment]
@alexvy86 It's my understanding that dotnet:2.1-sdk is replacing the aspnet-build image.  Can this fix or a better fix be applied?  Thanks.

**Comment by alexvy86** [comment]
@AceHack not for me to decide, I don't work at Microsoft :). The fix @natemcmaster [suggested](https://github.com/aspnet/aspnet-docker/pull/389#issuecomment-373553841) is for our projects' Dockerfiles though, so you can still do either of those.

I did notice that the [2.1-sdk image](https://github.com/dotnet/dotnet-docker/blob/c8af20264599d25cb508755fad6dd4c07677c9cd/2.1/sdk/stretch/amd64/Dockerfile) doesn't have the same workaround as the [2.0-sdk image](https://github.com/dotnet/dotnet-docker/blob/c8af20264599d25cb508755fad6dd4c07677c9cd/2.0/sdk/stretch/amd64/Dockerfile#L46), but I've since become of the opinion that copying the `*.csproj` files and running `dotnet restore` on those instead of the `*.sln` (which is when you might encounter this issue) is a better approach. Feel free to open an issue in the [images repo](https://github.com/dotnet/dotnet-docker) if you'd like to see the same workaround from this PR in the `2.1-sdk` image.

**Comment by AceHack** [comment]
@alexvy86 I have several csproj files and this just feels like a hack.   It would be nice to just be able to copy everything and have it ignore the dcproj inside the docker container.

**Comment by alexvy86** [comment]
Are they **independent** `csproj` files? As in, different executables/applications? If it's a single application that depends on class libraries defined in separate projects,, you only need to call `dotnet restore` on the main `csproj`. You can still copy everything (`*.sln` and `*.dcproj` included, if you want) into the container if that's easier, the change would only be that instead of doing `RUN dotnet restore` (on the folder of the `*.sln`), you do `RUN dotnet restore <path-to-main-csproj>`. 

I actually don't consider it a hack because in my mind the `*.dcproj` is not part of my application and it has no need to live in the container, even if it doesn't hurt anything.

**Comment by alexvy86** [comment]
In fact, the latest version of Visual Studio generates Dockerfiles that do just that, call `dotnet restore` directly on the main `*.csproj` file (and only the main one, if you have class libraries, as you can see below):
```
FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ConsoleApp2/ConsoleApp2.csproj ConsoleApp2/
COPY ClassLibrary1/ClassLibrary1.csproj ClassLibrary1/
RUN dotnet restore ConsoleApp2/ConsoleApp2.csproj
COPY . .
WORKDIR /src/ConsoleApp2
RUN dotnet build ConsoleApp2.csproj -c Release -o /app
```

**Pull request merged**
