### PR TITLE
September patch updates

### PR DESCRIPTION
**Pull request by natemcmaster**
FYI - CI is expected to fail initially until dependencies are available.

Updates:

- .NET Core 1.0.5 => 1.0.7
- .NET Core 1.1.2 => 1.1.4
- NodeJS 6.11.1 => 6.11.3
- Git 2.13.1 => 2.14.1

cc @muratg @JunTaoLuo 

Closes https://github.com/aspnet/aspnet-docker/issues/293

### CODE REVIEW

**Comment by muratg** [comment]
LGTM.  :shipit: once unblocked and @MichaelSimons is done with his part.

**Comment by natemcmaster** [comment]
Depends on https://github.com/dotnet/dotnet-docker/pull/292

**Comment by natemcmaster** [comment]
Added the update to Nano Server 10.0.14393.1715

**Comment by natemcmaster** [comment]
.NET Core patch updates are being delayed. I'm moving the Nano Server patch into a separate PR so we can get that in sooner.

**Comment by natemcmaster** [comment]
Updated with 1.0.7 and 1.1.4

**Pull request merged**
