### PR TITLE
Add lts tags to README.md

### LINKED ISSUE #168: Create LTS tag
Like latest, but for the slow, stable train.

### PR DESCRIPTION
**Pull request by natemcmaster**
Current LTS = 1.0.1. The `lts` tag, like `latest`, will move forward when LTS releases become available.

Resolve #168 

cc @glennc @richlander

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@richlander - I think we should have consistency with the dotnet repos regarding this tag.  Thoughts?

**Comment by natemcmaster** [comment]
Could we add a similar tag to microsoft/dotnet?

**Comment by MichaelSimons** [comment]
Yes I think that it makes sense to have them in both.

**Comment by glennc** [comment]
I am good with it going into both.

**Comment by natemcmaster** [comment]
Ok, I'll merge this and open an issue on dotnet-docker so we can track adding the equivalent lts tags to microsoft/dotnet.

**Pull request merged**
