### PR TITLE
Add beta7

### PR DESCRIPTION
**Pull request by PeterJausovec**
Adding Dockerfile for beta7.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
CI is failing:

>  Error: Could not find version 1.0.0-beta7 in feed https://www.nuget.org/api/v2

**Comment by glennc** [comment]
That would be because we haven't pushed a beta7 DNX to NuGet yet.

**Comment by ahmetalpbalkan** [comment]
@glennc thanks for the update. The change is LGTM, feel free to rebuild on circleCI when it's pushed and merge if the build passes.

**Comment by ahmetalpbalkan** [comment]
@glennc thanks for triggering the CI.  However it looks like beta7 is not tagged on Home repo. It fails on finding the samples

**Comment by glennc** [comment]
What are the requirements? There is a v1.0.0-beta7 tag. Do the tests run against latest samples on that tag?

**Comment by ahmetalpbalkan** [comment]
@glennc Sent you email internally. beta7 tag does not have the samples/1.0.0-beta7 directory. The CI has been systematically looking for that in the past 6 versions ans this is 3rd time fixing the samples are being forgotten. We've been retagging the release in the past 3 times just b/c of this.

**Comment by glennc** [comment]
Yeah, I added the beta7 folder but the tag was created a while back. The samples are not forgotten, but they cannot be done until there is a build to test them with. Tag will be updated shortly and I will respin the CI.

**Comment by ahmetalpbalkan** [comment]
@glennc Thanks.

**Comment by kichalla** [comment]
@ahmetalpbalkan CI is failing as we no longer support `dnx . kestrel` (the dot part)...it should either be `dnx kestrel`(in which case its the current directory) or `dnx -p <path-to-project.json> kestrel` (with the -p or --project switch)..this is a Beta7 change to dnx.

https://github.com/aspnet/aspnet-docker/blob/master/.ci/build-app-image.sh#L26

I have already updated the Home repo samples to have this change, could we use those docker files instead?
https://github.com/aspnet/Home/blob/v1.0.0-beta7/samples/1.0.0-beta7/HelloWeb/Dockerfile#L9

**Comment by ahmetalpbalkan** [comment]
@kichalla we should probably fix that CI script with some if clause like `version > beta7` somehow. I'll try to take a look today... 

However the error in the CI seemed a bit different to me, are we sure that's the error?:

image

**Comment by ahmetalpbalkan** [comment]
> could we use those docker files instead?

@kichalla sorry I misread your comment. Yes! we should use them if they are present. Let me see if I can send a fix and get Peter to rebase.

**Comment by ahmetalpbalkan** [comment]
CI is messed up... Merging anyway to unblock. Thanks @PeterJausovec.

**Pull request merged**
